title: 连享会的 Github 主页
description: 你可以 Fork 本仓库以创建自己的个人主页。
author: 连享会
theme: just-the-docs

url: "https://lianxhcn.github.io" 

# 设置导航菜单
nav:
  - title: "About"
    url: /about/
  - title: "Blogs"
    url: /blog/
  - title: "Codes"
    url: /codes/
#  - title: "Math"
#    url: /math/

# 站内搜索（可选）
search_enabled: true

compress_html:
  blanklines: true

# 支持 math 公式 https://github.com/pdmosses/test-nav/blob/master/_config.yml
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
