title: 连享会的 Github 主页
description: >
  A personal website powered by just-the-docs.
theme: just-the-docs

url: "https://lianxhcn.github.io" 

# 设置导航菜单
nav:
  - title: "About"
    url: /about/
  - title: "Blogs"
    url: /blog/
  - title: "Codes"
    url: /codes/
  - title: "Books"
    url: /books/

# 站内搜索（可选）
search_enabled: true
